# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /frontend

RUN apk update && apk upgrade
RUN apk add git

COPY package.json yarn.lock ./

RUN yarn install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the application will run on
EXPOSE 3000 24678

# Start the application
CMD [ "yarn", "dev" ]
